const UNICODE_DB = {
  // Overrides (High Risk)
  "U+202D": { name: "Left-to-Right Override", abbr: "LRO", char: "\u202D", category: "BiDi Override", risk: "🔴 High risk", desc: "Forces following characters to be treated as strong left-to-right.", use: "Forcing LTR display in RTL environments.", misuse: "Masking file extensions.", demoNormal: "file.txt", demoMod: "file\u202Dtxt", exp: "LRO forces the text direction, overriding natural behavior." },
  "U+202E": { name: "Right-to-Left Override", abbr: "RLO", char: "\u202E", category: "BiDi Override", risk: "🔴 High risk", desc: "Forces following characters to be treated as strong right-to-left.", use: "Forcing RTL display.", misuse: "Spoofing filenames (e.g., photo[RLO]gpj.exe).", demoNormal: "photo.jpg.exe", demoMod: "photo\u202Egpj.exe", exp: "RLO flips the rendering order of 'gpj.exe' to make it look like 'exe.jpg'." },
  
  // Embeddings (Medium Risk)
  "U+202A": { name: "Left-to-Right Embedding", abbr: "LRE", char: "\u202A", category: "BiDi Embedding", risk: "🟠 Medium risk", desc: "Treats embedded text as LTR.", use: "Embedding English in Arabic text.", misuse: "Obfuscating string flow.", demoNormal: "HELLO", demoMod: "\u202AHELLO\u202C", exp: "Sets a block of LTR text." },
  "U+202B": { name: "Right-to-Left Embedding", abbr: "RLE", char: "\u202B", category: "BiDi Embedding", risk: "🟠 Medium risk", desc: "Treats embedded text as RTL.", use: "Embedding Arabic in English text.", misuse: "Obfuscating string flow.", demoNormal: "WORLD", demoMod: "\u202BWORLD\u202C", exp: "Sets a block of RTL text." },
  "U+202C": { name: "Pop Directional Formatting", abbr: "PDF", char: "\u202C", category: "BiDi Formatting", risk: "🟠 Medium risk", desc: "Ends the scope of the last LRE, RLE, LRO, or RLO.", use: "Closing BiDi blocks.", misuse: "Part of BiDi exploits.", demoNormal: "End block", demoMod: "\u202C", exp: "Restores previous directional state." },

  // Isolates (Medium Risk)
  "U+2066": { name: "Left-to-Right Isolate", abbr: "LRI", char: "\u2066", category: "BiDi Isolate", risk: "🟠 Medium risk", desc: "Isolates LTR text from surrounding context.", use: "Safer embedding than LRE.", misuse: "Rare, but can cause rendering confusion.", demoNormal: "abc", demoMod: "\u2066abc\u2069", exp: "Isolates direction without affecting surroundings." },
  "U+2067": { name: "Right-to-Left Isolate", abbr: "RLI", char: "\u2067", category: "BiDi Isolate", risk: "🟠 Medium risk", desc: "Isolates RTL text.", use: "Safer embedding than RLE.", misuse: "Rare.", demoNormal: "abc", demoMod: "\u2067abc\u2069", exp: "Isolates RTL context." },
  "U+2068": { name: "First Strong Isolate", abbr: "FSI", char: "\u2068", category: "BiDi Isolate", risk: "🟠 Medium risk", desc: "Auto-detects direction of isolated text.", use: "Inserting user-generated text of unknown direction.", misuse: "Minimal.", demoNormal: "abc", demoMod: "\u2068abc\u2069", exp: "Auto-evaluates direction." },
  "U+2069": { name: "Pop Directional Isolate", abbr: "PDI", char: "\u2069", category: "BiDi Isolate", risk: "🟠 Medium risk", desc: "Ends scope of LRI, RLI, or FSI.", use: "Closing isolate blocks.", misuse: "Minimal.", demoNormal: "End isolate", demoMod: "\u2069", exp: "Closes the isolate block." },

  // Marks (Medium Risk)
  "U+061C": { name: "Arabic Letter Mark", abbr: "ALM", char: "\u061C", category: "BiDi Mark", risk: "🟠 Medium risk", desc: "Invisible character with strong RTL properties, specific to Arabic script layouts.", use: "Properly ordering mixed Arabic and numeric text.", misuse: "Padding or shifting characters in UI.", demoNormal: "HTML", demoMod: "HTML\u061C", exp: "Adjusts layout rules based on Arabic text behaviors." },
  "U+200E": { name: "Left-to-Right Mark", abbr: "LRM", char: "\u200E", category: "BiDi Mark", risk: "🟠 Medium risk", desc: "Invisible character with strong LTR properties.", use: "Fixing punctuation display in mixed RTL/LTR.", misuse: "Padding text invisibly.", demoNormal: "C++", demoMod: "C++\u200E", exp: "Forces the '++' to stay on the correct side in RTL." },
  "U+200F": { name: "Right-to-Left Mark", abbr: "RLM", char: "\u200F", category: "BiDi Mark", risk: "🟠 Medium risk", desc: "Invisible character with strong RTL properties.", use: "Fixing punctuation display.", misuse: "Padding.", demoNormal: "C++", demoMod: "C++\u200F", exp: "Forces layout behavior." },

  // Structural Separators (Low Risk, but affects BiDi)
  "U+2028": { name: "Line Separator", abbr: "LS", char: "\u2028", category: "Formatting", risk: "🟡 Low risk", desc: "Separates lines without creating a new paragraph. Affects BiDi scope limits.", use: "Line breaking in rich text environments.", misuse: "Historically used to break JavaScript string literals or obfuscate logs.", demoNormal: "Line1 Line2", demoMod: "Line1\u2028Line2", exp: "Forces a visual line break inside what is technically a single continuous string." },
  "U+2029": { name: "Paragraph Separator", abbr: "PS", char: "\u2029", category: "Formatting", risk: "🟡 Low risk", desc: "Separates paragraphs. Resets BiDi algorithms completely.", use: "Paragraph breaking.", misuse: "Obfuscation or exploiting string parsers.", demoNormal: "Para1 Para2", demoMod: "Para1\u2029Para2", exp: "Creates a structural paragraph break, resetting text directionality." },

  // Invisible / Formatting (Low Risk)
  "U+200B": { name: "Zero Width Space", abbr: "ZWSP", char: "\u200B", category: "Invisible", risk: "🟡 Low risk", desc: "Invisible break opportunity.", use: "Wrapping long URLs safely.", misuse: "Bypassing word filters (e.g., b[ZWSP]adword).", demoNormal: "HelloWorld", demoMod: "Hello\u200BWorld", exp: "Creates a line-break opportunity without a visible space." },
  "U+200C": { name: "Zero Width Non-Joiner", abbr: "ZWNJ", char: "\u200C", category: "Invisible", risk: "🟡 Low risk", desc: "Prevents ligatures.", use: "Persian/Arabic typography.", misuse: "Filter evasion.", demoNormal: "fi", demoMod: "f\u200Ci", exp: "Stops 'f' and 'i' from forming a ligature." },
  "U+200D": { name: "Zero Width Joiner", abbr: "ZWJ", char: "\u200D", category: "Invisible", risk: "🟡 Low risk", desc: "Forces ligatures or combines emojis.", use: "Complex emojis (👨‍👩‍👧).", misuse: "Obfuscation.", demoNormal: "👨👩", demoMod: "👨\u200D👩", exp: "Combines individual emojis." },
  "U+2060": { name: "Word Joiner", abbr: "WJ", char: "\u2060", category: "Invisible", risk: "🟡 Low risk", desc: "Prevents line breaks.", use: "Keeping words together.", misuse: "Obfuscation.", demoNormal: "A B", demoMod: "A\u2060B", exp: "Acts like a non-breaking space with zero width." },
  
  // Hyphens & Spaces (Low Risk)
  "U+00A0": { name: "Non-Breaking Space", abbr: "NBSP", char: "\u00A0", category: "Formatting", risk: "🟡 Low risk", desc: "Space that prevents line wrapping.", use: "Keeping units with numbers (e.g., 10 kg).", misuse: "Spoofing UI spacing.", demoNormal: "10 kg", demoMod: "10\u00A0kg", exp: "Visually identical to a space but prevents wrapping." },
  "U+00AD": { name: "Soft Hyphen", abbr: "SHY", char: "\u00AD", category: "Invisible", risk: "🟡 Low risk", desc: "Invisible unless text wraps at the end of a line.", use: "Indicating preferred hyphenation points.", misuse: "Hiding characters inside words to bypass filters (e.g., b[SHY]ad).", demoNormal: "HelloWorld", demoMod: "Hello\u00ADWorld", exp: "Remains invisible until line wrapping forces it to display." },
  "U+2011": { name: "Non-Breaking Hyphen", abbr: "NBHY", char: "\u2011", category: "Formatting", risk: "🟡 Low risk", desc: "A hyphen that prevents word wrapping.", use: "Keeping hyphenated words together (e.g., e-mail).", misuse: "Spoofing standard hyphens for domain lookalikes.", demoNormal: "e-mail", demoMod: "e\u2011mail", exp: "Prevents a line break from occurring at the hyphen." },

  // Invisible Math Operators (Low Risk)
  "U+2061": { name: "Function Application", abbr: "FUNC", char: "\u2061", category: "Invisible", risk: "🟡 Low risk", desc: "Indicates application of a function.", use: "Math formulas.", misuse: "Padding or string obfuscation.", demoNormal: "f(x)", demoMod: "f\u2061(x)", exp: "Acts as an invisible math syntax marker." },
  "U+2062": { name: "Invisible Times", abbr: "ITIM", char: "\u2062", category: "Invisible", risk: "🟡 Low risk", desc: "Indicates multiplication without a visible sign.", use: "Math layout (e.g., 2x).", misuse: "String obfuscation.", demoNormal: "2x", demoMod: "2\u2062x", exp: "Invisible multiplication operator." },
  "U+2063": { name: "Invisible Separator", abbr: "ISEP", char: "\u2063", category: "Invisible", risk: "🟡 Low risk", desc: "Separates indices or arguments invisibly.", use: "Math arrays.", misuse: "String obfuscation.", demoNormal: "i,j", demoMod: "i\u2063,j", exp: "Acts as an invisible comma equivalent." },
  "U+2064": { name: "Invisible Plus", abbr: "IPLUS", char: "\u2064", category: "Invisible", risk: "🟡 Low risk", desc: "Indicates addition invisibly.", use: "Fractions (e.g., 3 1/4).", misuse: "String obfuscation.", demoNormal: "3 1/4", demoMod: "3\u2064 1/4", exp: "Invisible addition operator." }
};
